# Copyright 2015-2016 F5 Networks Inc.
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#    http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
#
#


FROM  docker-registry.pdbld.f5net.com/f5-openstack-test/tempest:latest

RUN pip install git+https://github.com/openstack/neutron.git@stable/{{ branch }}
RUN pip install git+https://github.com/openstack/neutron-lbaas.git@stable/{{ branch }}
RUN mkdir -p /etc/tempest
RUN mkdir -p /root/f5-openstack-lbaasv2-driver
RUN tempest workspace register --name tempest_test --path /root/f5-openstack-lbaasv2-driver/
ADD run_tempest.sh /root/
WORKDIR /root/f5-openstack-lbaasv2-driver
ENTRYPOINT ["/root/run_tempest.sh"]
